### ISSUE TITLE
[Seção de Contato] Padding muito grande

### ISSUE THREAD

**Issue by patymori** [patymori/inovecapachos#2]
## Descrição
O tamanho de padding da seção de Contato está muito grande.

## Resultado Esperado
O tamanho do padding do topo da seção deve ficar menor e o padding de baixo pode ficar zerado.

**Comment by Serrones** [comment]
Aproveitei e ajustei o padding de todas as páginas, para que fique mais equilibrado.
https://github.com/patymori/inovecapachos/pull/6
